In [46]:
import numpy as np  
import pandas as pd

In [47]:
df = pd.read_csv("data/warehouse_messy_data.csv")

In [48]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Product ID      1000 non-null   int64
 1   Product Name    1000 non-null   str
 2   Category        1000 non-null   str
 3   Warehouse       1000 non-null   str
 4   Location        1000 non-null   str
 5   Quantity        842 non-null    str
 6   Price           793 non-null    float64
 7   Supplier        1000 non-null   str
 8   Status          1000 non-null   str
 9   Last Restocked  800 non-null    str
dtypes: float64(1), int64(1), str(8)
memory usage: 78.3 KB

In [49]:
df.shape

(1000, 10)

In [50]:
df.head(10)

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
0,1102,gadget y,ELECTRONICS,Warehouse 2,Aisle 1,300,9.99,Supplier C,In Stock,NaN
1,1435,gadget y,ELECTRONICS,Warehouse 2,Aisle 4,two hundred,19.99,Supplier C,Out of Stock,NaN
2,1860,widget a,CLOTHING,Warehouse 2,Aisle 3,100,19.99,Supplier B,In Stock,20/12/2022
3,1270,gadget z,TOYS,Warehouse 2,Aisle 4,50,49.99,Supplier B,In Stock,20/12/2022
4,1106,widget a,FURNITURE,Warehouse 3,Aisle 3,two hundred,9.99,Supplier D,Out of Stock,25/04/2023
5,1071,widget b,CLOTHING,Warehouse 3,Aisle 5,300,NaN,Supplier A,In Stock,20/12/2022
6,1700,widget a,CLOTHING,Warehouse 2,Aisle 2,two hundred,49.99,Supplier B,In Stock,20/12/2022
7,1020,widget c,CLOTHING,Warehouse 1,Aisle 5,two hundred,9.99,Supplier D,Out of Stock,20/12/2022
8,1614,gadget y,ELECTRONICS,Warehouse 3,Aisle 3,300,9.99,Supplier B,Out of Stock,05/03/2023
9,1121,widget b,TOYS,Warehouse 1,Aisle 2,50,19.99,Supplier C,Out of Stock,20/12/2022

In [51]:
df.describe(include='all')

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
count,1000.000000,1000,1000,1000,1000,842,793.000000,1000,1000,800
unique,NaN,6,4,3,5,5,NaN,4,3,4
top,NaN,gadget y,FURNITURE,Warehouse 1,Aisle 3,300,NaN,Supplier B,In Stock,20/12/2022
freq,NaN,177,265,349,211,177,NaN,288,340,218
mean,1503.929000,NaN,NaN,NaN,NaN,NaN,28.085839,NaN,NaN,NaN
std,289.998108,NaN,NaN,NaN,NaN,NaN,14.686312,NaN,NaN,NaN
min,1000.000000,NaN,NaN,NaN,NaN,NaN,9.990000,NaN,NaN,NaN
25%,1242.750000,NaN,NaN,NaN,NaN,NaN,19.990000,NaN,NaN,NaN
50%,1505.000000,NaN,NaN,NaN,NaN,NaN,29.990000,NaN,NaN,NaN
75%,1757.250000,NaN,NaN,NaN,NaN,NaN,49.990000,NaN,NaN,NaN
max,1998.000000,NaN,NaN,NaN,NaN,NaN,49.990000,NaN,NaN,NaN

In [52]:
df['Quantity'].unique()

<StringArray>
['300', 'two hundred', '100', '50', nan, '150']
Length: 6, dtype: str

In [53]:
df['Product ID'].nunique()
df[df['Product ID']==1098]

,Product ID,Product Name,Category,Warehouse,Location,Quantity,Price,Supplier,Status,Last Restocked
166,1098,gadget x,CLOTHING,Warehouse 1,Aisle 3,50,19.99,Supplier A,In Stock,05/03/2023
377,1098,gadget y,FURNITURE,Warehouse 3,Aisle 1,two hundred,29.99,Supplier C,In Stock,NaN
401,1098,widget b,ELECTRONICS,Warehouse 2,Aisle 4,300,49.99,Supplier C,Low Stock,25/04/2023
472,1098,widget b,CLOTHING,Warehouse 2,Aisle 1,150,49.99,Supplier A,Out of Stock,NaN
482,1098,widget c,FURNITURE,Warehouse 3,Aisle 4,two hundred,29.99,Supplier C,Out of Stock,20/12/2022
756,1098,widget c,TOYS,Warehouse 1,Aisle 2,300,49.99,Supplier D,Out of Stock,NaN
805,1098,widget b,TOYS,Warehouse 2,Aisle 2,50,29.99,Supplier B,Out of Stock,NaN

In [54]:
df['Quantity'].dtype

In [55]:
df['Last Restocked'].dtype

In [56]:
df['Product ID'].dtype

dtype('int64')

In [57]:
out =df[df['Status']=="Out of Stock"]
out[out['Quantity']=='0']

Empty DataFrame
Columns: [Product ID, Product Name, Category, Warehouse, Location, Quantity, Price, Supplier, Status, Last Restocked]
Index: []

## Damage Report

**Category**
- Capitalised values

**Quantity**
- Numbers in names: 'two hundred'
- Missing/Null Values

**Price**
- Missing/Null Values

**Last Restocked**
- Missing dates

**Product ID**
- Multiple difference products have the same product ID

**Mismacting Dtypes**
- Quantity should be an integer not string
- Last restocked should be in datetime format not string
- Product ID doesn't need to be integer

**Status**
- Many products have an out of stock status but the values in their quantity columns are not zero

**Making The Columns into Snakecase**

In [58]:
df.columns = df.columns.str.lower()
df.columns = df.columns.str.strip()
df.columns = df.columns.str.replace(" ","_")
df.columns

Index(['product_id', 'product_name', 'category', 'warehouse', 'location',
       'quantity', 'price', 'supplier', 'status', 'last_restocked'],
      dtype='str')

**Blank Rows/Columns**

In [59]:
df.isna().all().sum()

np.int64(0)

In [60]:
df.isna().all(axis=1).sum()

np.int64(0)

**Duplicated Rows**

In [61]:
df.duplicated().sum()

np.int64(0)

**Product ID Flag**
- The Product ID is not a valid key/index as many id's map to multiple products at once
- 238 Product IDs map to more than one product
- Can't be used as a key to join tables or a way of counting number of distinct products
- It has been retained so as to not delete any evidence but do not use as the unit of analysis, use each row instead

In [62]:
products = df.groupby('product_id')['product_name'].nunique()
products

product_id
1000    1
1001    3
1004    2
1007    1
1008    2
       ..
1991    1
1992    2
1995    2
1996    1
1998    1
Name: product_name, Length: 615, dtype: int64

In [63]:
mask = products[products>1].index
mask.shape[0]

238

In [64]:
print(f"{mask.shape[0]} product IDs out of {products.shape[0]} belong to more than one product")

238 product IDs out of 615 belong to more than one product

**Product Name**
- Padded whitespaces and lowercase
- Must normalise by removing padding and making into a title

In [65]:
df['product_name']=df['product_name'].str.strip()
df['product_name']=df['product_name'].str.title()
df['product_name'].nunique()

6

**Category**
- All uppercase letters must be normalised to title case

In [66]:
df['category'] = df['category'].str.title()
df['category'].unique()

<StringArray>
['Electronics', 'Clothing', 'Toys', 'Furniture']
Length: 4, dtype: str

**Status**
- 3 values, all in appropriate format
- No cleaning needed

In [67]:
df['status'].value_counts()

status
In Stock        340
Out of Stock    332
Low Stock       328
Name: count, dtype: int64

**Price**
- 207 Missing values out 1000 total values
- There are 4 price values for each product name and the name of the product doesn't indicate which price it is as all product names have the same 4 price values
    - Same goes for category
- No imputation of price as we have no real way of guessing a products price thus we leave as blank

In [68]:
tot = len(df)

In [69]:
miss = df['price'].isna().sum()

In [70]:
print(f"{miss/tot *100:.0f}% of products have a missing Price")

21% of products have a missing Price

In [71]:
df.groupby('product_name')['price'].unique()

product_name
Gadget X    [49.99, nan, 19.99, 29.99, 9.99]
Gadget Y    [9.99, 19.99, 49.99, nan, 29.99]
Gadget Z    [49.99, 9.99, 29.99, 19.99, nan]
Widget A    [19.99, 9.99, 49.99, nan, 29.99]
Widget B    [nan, 19.99, 29.99, 49.99, 9.99]
Widget C    [9.99, 49.99, 19.99, 29.99, nan]
Name: price, dtype: object

In [72]:
df.groupby('category')['price'].unique()

category
Clothing       [19.99, nan, 49.99, 9.99, 29.99]
Electronics    [9.99, 19.99, 49.99, 29.99, nan]
Furniture      [9.99, 49.99, 29.99, nan, 19.99]
Toys           [49.99, 19.99, 9.99, nan, 29.99]
Name: price, dtype: object

**Quantity**
- Column in string format instead of integer
- The words 'two hundred' appear instead of 200
- Thus two hundred changed to 200 and column is converted to integer

In [73]:
df.groupby("category")['quantity'].unique()

category
Clothing       [100, 300, two hundred, nan, 50, 150]
Electronics    [300, two hundred, 100, 150, nan, 50]
Furniture      [two hundred, 50, 300, 100, nan, 150]
Toys           [50, 150, 300, two hundred, nan, 100]
Name: quantity, dtype: object

In [74]:
df.groupby("product_name")['quantity'].unique()

product_name
Gadget X    [100, 300, 50, 150, nan, two hundred]
Gadget Y    [300, two hundred, 150, 100, nan, 50]
Gadget Z    [50, two hundred, 150, 300, nan, 100]
Widget A    [100, two hundred, nan, 50, 300, 150]
Widget B    [300, 50, 100, 150, nan, two hundred]
Widget C    [two hundred, 150, 300, 100, 50, nan]
Name: quantity, dtype: object

In [75]:
df['quantity'] = df['quantity'].str.replace("two hundred", "200")
df['quantity'] = pd.to_numeric(df['quantity'], errors='coerce').astype('Int64')
df['quantity']

0      300
1      200
2      100
3       50
4      200
      ...
995    100
996    300
997    150
998    100
999    100
Name: quantity, Length: 1000, dtype: Int64

**Last Restocked**
- Missing date values left as null
- Converted from string format to US datetime format

In [76]:
df['last_restocked'] = pd.to_datetime(df['last_restocked'], format='%d/%m/%Y')
df['last_restocked'].dtype

dtype('<M8[us]')

In [77]:
df['last_restocked'].min()

Timestamp('2022-12-20 00:00:00')

In [78]:
df['last_restocked'].max()

Timestamp('2023-04-25 00:00:00')

In [79]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 10 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   product_id      1000 non-null   int64
 1   product_name    1000 non-null   str
 2   category        1000 non-null   str
 3   warehouse       1000 non-null   str
 4   location        1000 non-null   str
 5   quantity        842 non-null    Int64
 6   price           793 non-null    float64
 7   supplier        1000 non-null   str
 8   status          1000 non-null   str
 9   last_restocked  800 non-null    datetime64[us]
dtypes: Int64(1), datetime64[us](1), float64(1), int64(1), str(6)
memory usage: 79.2 KB

In [80]:
df['supplier'].unique()

<StringArray>
['Supplier C', 'Supplier B', 'Supplier D', 'Supplier A']
Length: 4, dtype: str

In [82]:
assert df['quantity'].dtype == 'Int64', "Quantity is not in integer format"
assert df['price'].dtype == 'float64', "Price is not in float format"
assert df['last_restocked'].dtype == "datetime64[us]", "Last Restocked is not in datetime format"
assert df['product_name'].isna().any()==False, "Product Name has null values"
assert df['category'].isna().any()==False, "Cateogry has null values"
assert df['warehouse'].isna().any()==False, "Warehouse has null values"
assert df['location'].isna().any()==False, " Location has null values"
assert df['supplier'].isna().any()==False, "Supplier has null values"
assert df['status'].isna().any()==False, "Status has null values"
cat = {"Clothing", "Electronics", "Furniture", "Toys"}
assert set(df['category'].unique()) <= cat, "Categories do not have their cannonical values"
stat = {"In Stock", "Out of Stock", "Low Stock"}
assert set(df['status'].unique()) <= stat, "Status does not have its cannonical values"
ware = {"Warehouse 2", "Warehouse 3", "Warehouse 1"}
assert set(df['warehouse'].unique()) <= ware, "Warehouse does not have its cannonical values"
aisle = {"Aisle 1", "Aisle 2", "Aisle 3", "Aisle 4", "Aisle 5"}
assert set(df['location'].unique()) <= aisle, "Location does not have its cannonical values"
sup = {"Supplier A", "Supplier B", "Supplier C", "Supplier D"}
assert set(df['supplier'].unique()) <= sup, "Supplier does not have its cannonical values"
assert df.shape[0] == 1000, "Invalid Rows"

In [ ]:
df.to_csv('data/warehouse_clean.csv', index=False)

: